/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms_main;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;

/**
 *
 * @author mtari_000
 */
public class booking_records extends javax.swing.JFrame {

    /**
     * Creates new form Reservation
     */
    public booking_records() {
        initComponents();
    }
    Vector<String> header=new Vector<>();
    Vector<Vector<String>> reservation_records=new Vector<Vector<String>>();
    JScrollPane pane; 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Booking Records");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 120, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms_main/logo.jpg"))); // NOI18N
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        jLabel4.setText("ID:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 30, 30));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Check In");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, 120, 50));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Reservation");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 120, 50));

        jTable2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 460, 350));

        jTable3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 460, 350));

        jLabel5.setText("ID:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 30, 30));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 120, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Check-In Records");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 280, 30));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Reservations Records");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 280, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms_main/menu.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         header.clear();
        reservation_records.clear();
        
        try
        {
                      

           
            
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        Connection con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=hotel_management_system;user=sa;password=sqlserver123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from check_in");
           
            
             while(rs.next())
            {
                int reservation=rs.getInt("reservation");
                String contact=rs.getString("contact");
                String f_name=rs.getString("first_name");
                String l_name=rs.getString("last_name");
                String addr=rs.getString("address");
                String country=rs.getString("country");
                String company=rs.getString("company");
                String id_type=rs.getString("id_type");
                String id_no=rs.getString("id_no");
                String vehical_make=rs.getString("vehical_make");
                int model=rs.getInt("model");
                String reg_no=rs.getString("registration_no");
                int room_no=rs.getInt("room_no");
                String date_in=String.valueOf(rs.getDate("date_in"));
                String date_out=String.valueOf(rs.getDate("date_out"));
                String rate_type=rs.getString("rate_type");
                int rate=rs.getInt("rate");
                int no_of_days=rs.getInt("no_of_days");
                int no_of_adults=rs.getInt("no_of_adults");
                int no_of_childerns=rs.getInt("no_of_childerns");
                int lunch=rs.getInt("lunch");
                int tea=rs.getInt("tea");
                int dinner=rs.getInt("dinner");
                int other_charges=rs.getInt("other_charges");
                int sub_total=rs.getInt("sub_total");
                int discount=rs.getInt("discount");
                int total=rs.getInt("total");
                int amount_paid=rs.getInt("amount_paid");
                int balance=rs.getInt("balance");
                String note=rs.getString("note");
                
                        
                //this vector is ised for add one row into cust_data
                Vector<String> row=new Vector<>();
                
                row.add(""+reservation);
                row.add(contact); 
                row.add(f_name);
                row.add(l_name);
                row.add(addr);
                row.add(country);
                row.add(company);
                row.add(id_type);
                row.add(id_no);
                row.add(vehical_make);
                row.add(""+model);
                row.add(reg_no);
                row.add(""+room_no);
                row.add(date_in);
                row.add(date_out);
                row.add(rate_type);
                row.add(""+rate);
                row.add(""+no_of_days);
                row.add(""+no_of_adults);
                row.add(""+no_of_childerns);
                row.add(""+lunch);
                row.add(""+tea);
                row.add(""+dinner);
                row.add(""+other_charges);
                row.add(""+sub_total);
                row.add(""+discount);
                row.add(""+total);
                row.add(""+amount_paid);
                row.add(""+balance);
                row.add(note);
                
              reservation_records.add(row);
            }            
                header.add("reservation");
                header.add("contact"); 
                header.add("first_name");
                header.add("last_name");
                header.add("address");
                header.add("country");
                header.add("company");
                header.add("id_type");
                header.add("id_no");
                header.add("vehical_make");
                header.add("model");
                header.add("registration_no");
                header.add("room_no");
                header.add("date_in");
                header.add("date_out");
                header.add("rate_type");
                header.add("rate");
                header.add("no_of_days");
                header.add("no_of_adults");
                header.add("no_of_childerns");
                header.add("lunch");
                header.add("tea");
                header.add("dinner");
                header.add("other_charges");
                header.add("sub_total");
                header.add("discount");
                header.add("total");
                header.add("amount_paid");
                header.add("balance");
                header.add("note");
           
            
           jTable2.setModel(new DefaultTableModel(reservation_records,header));
            
        }
        catch(ClassNotFoundException | SQLException e)
        {
            
        }
        
        catch(Exception ex)
        {
            
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          header.clear();
        reservation_records.clear();
        
        try
        {
                      

           
            
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        Connection con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=hotel_management_system;user=sa;password=sqlserver123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from booking_records");
           
            
             while(rs.next())
            {
                int reservation=rs.getInt("reservation");
                String contact=rs.getString("contact");
                String f_name=rs.getString("first_name");
                String l_name=rs.getString("last_name");
                String addr=rs.getString("address");
                String country=rs.getString("country");
                String company=rs.getString("company");
                String id_type=rs.getString("id_type");
                String id_no=rs.getString("id_no");
                String vehical_make=rs.getString("vehical_make");
                int model=rs.getInt("model");
                String reg_no=rs.getString("registration_no");
                int room_no=rs.getInt("room_no");
                String date_in=String.valueOf(rs.getDate("date_in"));
                String date_out=String.valueOf(rs.getDate("date_out"));
                String rate_type=rs.getString("rate_type");
                int rate=rs.getInt("rate");
                int no_of_days=rs.getInt("no_of_days");
                int no_of_adults=rs.getInt("no_of_adults");
                int no_of_childerns=rs.getInt("no_of_childerns");
                int lunch=rs.getInt("lunch");
                int tea=rs.getInt("tea");
                int dinner=rs.getInt("dinner");
                int other_charges=rs.getInt("other_charges");
                int sub_total=rs.getInt("sub_total");
                int discount=rs.getInt("discount");
                int total=rs.getInt("total");
                int amount_paid=rs.getInt("amount_paid");
                int balance=rs.getInt("balance");
                String note=rs.getString("note");
                
                        
                //this vector is ised for add one row into cust_data
                Vector<String> row=new Vector<>();
                
                row.add(""+reservation);
                row.add(contact); 
                row.add(f_name);
                row.add(l_name);
                row.add(addr);
                row.add(country);
                row.add(company);
                row.add(id_type);
                row.add(id_no);
                row.add(vehical_make);
                row.add(""+model);
                row.add(reg_no);
                row.add(""+room_no);
                row.add(date_in);
                row.add(date_out);
                row.add(rate_type);
                row.add(""+rate);
                row.add(""+no_of_days);
                row.add(""+no_of_adults);
                row.add(""+no_of_childerns);
                row.add(""+lunch);
                row.add(""+tea);
                row.add(""+dinner);
                row.add(""+other_charges);
                row.add(""+sub_total);
                row.add(""+discount);
                row.add(""+total);
                row.add(""+amount_paid);
                row.add(""+balance);
                row.add(note);
                
              reservation_records.add(row);
            }            
                header.add("reservation");
                header.add("contact"); 
                header.add("first_name");
                header.add("last_name");
                header.add("address");
                header.add("country");
                header.add("company");
                header.add("id_type");
                header.add("id_no");
                header.add("vehical_make");
                header.add("model");
                header.add("registration_no");
                header.add("room_no");
                header.add("date_in");
                header.add("date_out");
                header.add("rate_type");
                header.add("rate");
                header.add("no_of_days");
                header.add("no_of_adults");
                header.add("no_of_childerns");
                header.add("lunch");
                header.add("tea");
                header.add("dinner");
                header.add("other_charges");
                header.add("sub_total");
                header.add("discount");
                header.add("total");
                header.add("amount_paid");
                header.add("balance");
                header.add("note");
           
            
           jTable3.setModel(new DefaultTableModel(reservation_records,header));
            
        }
        catch(ClassNotFoundException | SQLException e)
        {
            
        }
        
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        header.clear();
        reservation_records.clear();
        
        try
        {
                    int id=Integer.parseInt(jTextField1.getText());   

           
            
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        Connection con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=hotel_management_system;user=sa;password=sqlserver123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from booking_records where reservation='"+id+"'");
           
            
            
            while(rs.next())
            {
                int reservation=rs.getInt("reservation");
                String contact=rs.getString("contact");
                String f_name=rs.getString("first_name");
                String l_name=rs.getString("last_name");
                String addr=rs.getString("address");
                String country=rs.getString("country");
                String company=rs.getString("company");
                String id_type=rs.getString("id_type");
                String id_no=rs.getString("id_no");
                String vehical_make=rs.getString("vehical_make");
                int model=rs.getInt("model");
                String reg_no=rs.getString("registration_no");
                int room_no=rs.getInt("room_no");
                String date_in=String.valueOf(rs.getDate("date_in"));
                String date_out=String.valueOf(rs.getDate("date_out"));
                String rate_type=rs.getString("rate_type");
                int rate=rs.getInt("rate");
                int no_of_days=rs.getInt("no_of_days");
                int no_of_adults=rs.getInt("no_of_adults");
                int no_of_childerns=rs.getInt("no_of_childerns");
                int lunch=rs.getInt("lunch");
                int tea=rs.getInt("tea");
                int dinner=rs.getInt("dinner");
                int other_charges=rs.getInt("other_charges");
                int sub_total=rs.getInt("sub_total");
                int discount=rs.getInt("discount");
                int total=rs.getInt("total");
                int amount_paid=rs.getInt("amount_paid");
                int balance=rs.getInt("balance");
                String note=rs.getString("note");
                
                        
                //this vector is ised for add one row into cust_data
                Vector<String> row=new Vector<>();
                
                row.add(""+reservation);
                row.add(contact); 
                row.add(f_name);
                row.add(l_name);
                row.add(addr);
                row.add(country);
                row.add(company);
                row.add(id_type);
                row.add(id_no);
                row.add(vehical_make);
                row.add(""+model);
                row.add(reg_no);
                row.add(""+room_no);
                row.add(date_in);
                row.add(date_out);
                row.add(rate_type);
                row.add(""+rate);
                row.add(""+no_of_days);
                row.add(""+no_of_adults);
                row.add(""+no_of_childerns);
                row.add(""+lunch);
                row.add(""+tea);
                row.add(""+dinner);
                row.add(""+other_charges);
                row.add(""+sub_total);
                row.add(""+discount);
                row.add(""+total);
                row.add(""+amount_paid);
                row.add(""+balance);
                row.add(note);
                
              reservation_records.add(row);
            }            
                header.add("reservation");
                header.add("contact"); 
                header.add("first_name");
                header.add("last_name");
                header.add("address");
                header.add("country");
                header.add("company");
                header.add("id_type");
                header.add("id_no");
                header.add("vehical_make");
                header.add("model");
                header.add("registration_no");
                header.add("room_no");
                header.add("date_in");
                header.add("date_out");
                header.add("rate_type");
                header.add("rate");
                header.add("no_of_days");
                header.add("no_of_adults");
                header.add("no_of_childerns");
                header.add("lunch");
                header.add("tea");
                header.add("dinner");
                header.add("other_charges");
                header.add("sub_total");
                header.add("discount");
                header.add("total");
                header.add("amount_paid");
                header.add("balance");
                header.add("note");
           
          // pane = new JScrollPane(jTable3); 
           jTable3.setModel(new DefaultTableModel(reservation_records,header));
           
        }
        catch(ClassNotFoundException | SQLException e)
        {
            
        }
          catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        header.clear();
        reservation_records.clear();
        
        try
        {
                    int id=Integer.parseInt(jTextField1.getText());   

           
            
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        Connection con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=hotel_management_system;user=sa;password=sqlserver123");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from check_in where reservation='"+id+"'");
           
            
            
            while(rs.next())
            {
                int reservation=rs.getInt("reservation");
                String contact=rs.getString("contact");
                String f_name=rs.getString("first_name");
                String l_name=rs.getString("last_name");
                String addr=rs.getString("address");
                String country=rs.getString("country");
                String company=rs.getString("company");
                String id_type=rs.getString("id_type");
                String id_no=rs.getString("id_no");
                String vehical_make=rs.getString("vehical_make");
                int model=rs.getInt("model");
                String reg_no=rs.getString("registration_no");
                int room_no=rs.getInt("room_no");
                String date_in=String.valueOf(rs.getDate("date_in"));
                String date_out=String.valueOf(rs.getDate("date_out"));
                String rate_type=rs.getString("rate_type");
                int rate=rs.getInt("rate");
                int no_of_days=rs.getInt("no_of_days");
                int no_of_adults=rs.getInt("no_of_adults");
                int no_of_childerns=rs.getInt("no_of_childerns");
                int lunch=rs.getInt("lunch");
                int tea=rs.getInt("tea");
                int dinner=rs.getInt("dinner");
                int other_charges=rs.getInt("other_charges");
                int sub_total=rs.getInt("sub_total");
                int discount=rs.getInt("discount");
                int total=rs.getInt("total");
                int amount_paid=rs.getInt("amount_paid");
                int balance=rs.getInt("balance");
                String note=rs.getString("note");
                
                        
                //this vector is ised for add one row into cust_data
                Vector<String> row=new Vector<>();
                
                row.add(""+reservation);
                row.add(contact); 
                row.add(f_name);
                row.add(l_name);
                row.add(addr);
                row.add(country);
                row.add(company);
                row.add(id_type);
                row.add(id_no);
                row.add(vehical_make);
                row.add(""+model);
                row.add(reg_no);
                row.add(""+room_no);
                row.add(date_in);
                row.add(date_out);
                row.add(rate_type);
                row.add(""+rate);
                row.add(""+no_of_days);
                row.add(""+no_of_adults);
                row.add(""+no_of_childerns);
                row.add(""+lunch);
                row.add(""+tea);
                row.add(""+dinner);
                row.add(""+other_charges);
                row.add(""+sub_total);
                row.add(""+discount);
                row.add(""+total);
                row.add(""+amount_paid);
                row.add(""+balance);
                row.add(note);
                
              reservation_records.add(row);
            }            
                header.add("reservation");
                header.add("contact"); 
                header.add("first_name");
                header.add("last_name");
                header.add("address");
                header.add("country");
                header.add("company");
                header.add("id_type");
                header.add("id_no");
                header.add("vehical_make");
                header.add("model");
                header.add("registration_no");
                header.add("room_no");
                header.add("date_in");
                header.add("date_out");
                header.add("rate_type");
                header.add("rate");
                header.add("no_of_days");
                header.add("no_of_adults");
                header.add("no_of_childerns");
                header.add("lunch");
                header.add("tea");
                header.add("dinner");
                header.add("other_charges");
                header.add("sub_total");
                header.add("discount");
                header.add("total");
                header.add("amount_paid");
                header.add("balance");
                header.add("note");
           
            // pane = new JScrollPane(jTable2);  
           jTable2.setModel(new DefaultTableModel(reservation_records,header));
            
        }
        catch(ClassNotFoundException | SQLException e)
        {
            
        }
          catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking_records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking_records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking_records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking_records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booking_records().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
